### ISSUE TITLE
Unable to use Junctions with Typescript 2.9

### ISSUE THREAD

**Issue by dupski** [jamesknelson/junctions#30] opened 2018-07-11 02:38 UTC
I really like the idea and simplicity of this library, however I am unable to use it in a TypeScript 2.9 project with strict mode turned on.

Despite setting the 'rootDir' and 'excludes' settings in my TS Config to exclude `node_modules`, the typescript compiler still tries to compile the `src` files shipped in the npm module, which is failing with a ton of errors (a small subset pasted below).

(I've also tried explicitly setting 'excludes' in my webpack config)

```
ERROR in /Users/russell/code/testapp/node_modules/junctions/src/Route.ts
[tsl] ERROR in /Users/russell/code/testapp/node_modules/junctions/src/Route.ts(16,18)
      TS2430: Interface 'JunctionRoute<J>' incorrectly extends interface 'Route'.
  Types of property '0' are incompatible.
    Type 'Junction<J>' is not assignable to type 'RouteSegment'.
      Type 'Junction<J>' is not assignable to type 'Junction<JunctionTemplate<any, any, any>>'.
        Types of property 'activeRoute' are incompatible.
          Type 'JunctionDescendentSegments<J>' is not assignable to type 'JunctionDescendentSegments<JunctionTemplate<any, any, any>>'.
            Type 'JunctionTemplate<any, any, any>' is not assignable to type 'J'.

ERROR in /Users/russell/code/testapp/node_modules/junctions/src/Route.ts
[tsl] ERROR in /Users/russell/code/testapp/node_modules/junctions/src/Route.ts(17,5)
      TS2412: Property '0' of type 'Junction<J>' is not assignable to numeric index type 'RouteSegment'.

ERROR in /Users/russell/code/testapp/node_modules/junctions/src/Route.ts
[tsl] ERROR in /Users/russell/code/testapp/node_modules/junctions/src/Route.ts(152,5)
      TS2412: Property '0' of type '{ [K in keyof J["children"]]: J["children"][K] extends AsyncObjectContainer<infer T> ? { Junction...' is not assignable to numeric index type 'RouteSegment'.

ERROR in /Users/russell/code/testapp/node_modules/junctions/src/PageTemplate.ts
[tsl] ERROR in /Users/russell/code/testapp/node_modules/junctions/src/PageTemplate.ts(3,1)
      TS6192: All imports in import declaration are unused.

ERROR in /Users/russell/code/testapp/node_modules/junctions/src/PageTemplate.ts
[tsl] ERROR in /Users/russell/code/testapp/node_modules/junctions/src/PageTemplate.ts(4,10)
      TS6133: 'Page' is declared but its value is never read.
```

My feeling is it would be better to ship the npm package without the source files (just the dist folder with the .d.ts typings), then maybe ship a seperate `-src` package for peeps that want to compile the source themselves?

**Comment by jamesknelson** [comment] 2018-07-11 02:49
Thanks for trying out Junctions!

I actually use the src directory as typings, but I'm stuck on TypeScript 2.8 due to a regression in 2.9 which won't be fixed until 3.0, so hadn't encountered these errors.

I think there's two ways you could fix this:

1. Remove the `types` property from junctions' package.json in your local copy (iirc, it tells typescript to use the src directory for typings)

2. If you could update the typings in src to work in 2.9 (and not break 2.8), I'd be happy to merge it.

**Comment by dupski** [comment] 2018-07-11 03:13
Thanks for coming back so quickly! I've had to switch over to react-router for now to get moving on this project (sad times) however I'll try to have a look in the next few weeks if I have time :)

**Comment by jamesknelson** [comment] 2018-07-11 03:16
No worries. I'll close this for now, but feel free to reopen if you get time try and fix it. Hope your project goes well!

**Closed by jamesknelson** 2018-07-11 03:16 UTC
